### your site title here

title: Bronwyn Roe
url: https://bronwynroe.com
email: bronwync.roe@gmail.com
description: Bronwyn Roe is a painter and video artist based in New York City. Portfolio site created by Joel Bitar, www.joelbitar.space

highlighter: rouge
markdown: kramdown
### exclude the instructions / write-up in the README.md

collections:
- gallery

# Tracker
analytics: UA-83979019-1

#optimization
#compress.html
compress_html:
  clippings: [html,div, p, ul, td, h1, h2, h3, h4,link, meta, footer, nav, img, header, hr, br, head, style, li, ul, ol, time, main, script, title]
  comments: ["<!-- ", " -->"]
  endings: [all]
  ignore:
    envs: [local]
  blanklines: false
  profile: false
  startings: []


sass:
 style: compressed

exclude:
- README.md


gems: [jekyll-seo-tag, jekyll-paginate]
